language: ruby
rvm:
  - 2.1.1

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database Instagram_test;' -U postgres
  - cp config/secrets.yml.travis config/secrets.yml
  - bundle exec rake db:migrate

test:
  adapter: postgresql
  database: Instagram_test
  username: postgres

